package io.github.matthewjones372.kestrel.record

import kotlin.time.Duration

/**
 * The draft as Kotlin source somebody edits and commits.
 *
 * Source rather than a `Scenario` read at run time. A recording is a first
 * draft and most of it wants deleting; a file that is re-read on every run is
 * one nobody edits, so the forty CDN requests and the expired token stay in it
 * forever. Source is reviewable in a pull request, diffable when the flow
 * changes, and mostly deletable — which is what a reader does with a draft and
 * cannot do with a file.
 */
fun Draft.asKotlin(packageName: String, scenario: String, from: String): String =
    (
        headerLines(from) +
            "package $packageName" +
            "" +
            imports() +
            "" +
            baseLines() +
            captures.map { "val ${it.name}: SessionKey<String> = sessionKey(\"${it.name}\")" } +
            (if (captures.isEmpty()) emptyList() else listOf("")) +
            "val $scenario: Scenario = scenario(\"$scenario\") {" +
            steps.flatMap { it.lines() }.map { line -> if (line.isEmpty()) line else "    $line" } +
            "}"
        ).joinToString(separator = "\n", postfix = "\n")

private fun headerLines(from: String): List<String> = listOf(
    "// Generated by kestrel-record from $from.",
    "//",
    "// Edit it, commit it, delete most of it. A recording is a first draft: it",
    "// holds every request a browser made, the values one answer put in the next",
    "// request, and none of the judgement about which of them is the test.",
    "//",
    "// Every credential it carried was dropped. Each one left a TODO where it was,",
    "// which stops this file running until somebody decides what belongs there.",
    "",
)

private fun Draft.imports(): List<String> = buildList {
    add("import io.github.matthewjones372.kestrel.Scenario")
    if (captures.isNotEmpty()) add("import io.github.matthewjones372.kestrel.SessionKey")
    add("import io.github.matthewjones372.kestrel.http.http")
    add("import io.github.matthewjones372.kestrel.scenario")
    if (captures.isNotEmpty()) add("import io.github.matthewjones372.kestrel.sessionKey")
    add("import io.github.matthewjones372.kestrel.step")
}.sorted()

private fun Draft.baseLines(): List<String> {
    if (baseUrl == null) return listOf("private val api = http", "")
    val others = elsewhere.takeIf { it.isNotEmpty() }
        ?.let { "// The recording also went to ${it.joinToString()}; those requests are absolute below." }
    return listOfNotNull(others, "private val api = http.baseUrl(${baseUrl.quoted()})", "")
}

private fun DraftStep.lines(): List<String> = buildList {
    if (after > Duration.ZERO) {
        add("// The recorded gap before this was $after — one person's think time, not a rate line.")
    }
    if (stoodFor > 1) add("// Stood for $stoodFor requests differing only by a segment.")
    if (unanswered) {
        add("// The recording got no answer to this one, so 200 is a guess rather than what was seen.")
    }
    dropped.forEach { add("// The recording's $it header was dropped; the TODO below says where it went.") }
    droppedParameters.forEach {
        add("// The recording's `$it` query parameter was a credential and was dropped with its value.")
    }
    maybe.distinct().forEach {
        add("// \"$it\" was also in an earlier answer. It may want a capture; it is too short to be sure.")
    }
    addAll(execLines())
}

private val DraftStep.named: String get() = "$method $path"

/**
 * The request as a chain of calls, one per line.
 *
 * Built as text rather than as a tree, because the tree is a `Request` and this
 * runs before there is one: a generator that built the value it is generating
 * source for would still have to print it. Every width decision here is about
 * the 120 columns this repository formats to — the generated file is held to
 * them like any other, or `spotlessCheck` moves it and the test that compares
 * it fails.
 */
private fun DraftStep.execLines(): List<String> {
    val chain = chain()
    val opening = "api.${method.lowercase()}(${path.quoted()})"
    val together = "exec(step(${named.quoted()}), $opening)"
    if (chain.isEmpty() && together.length + INDENT <= WIDTH) return listOf(together)
    return listOf("exec(", "    step(${named.quoted()}),", "    $opening") +
        chain.dropLast(1).map { "        $it" } +
        listOfNotNull(chain.lastOrNull()?.let { "        $it," }) +
        ")"
}

private fun DraftStep.chain(): List<String> = buildList {
    headers.forEach { add(".header(${it.name.quoted()}, ${it.value.quoted()})") }
    dropped.forEach { add(".header(${it.quoted()}, TODO(${todoFor(it).quoted()}))") }
    body?.let { add(".body(${it.quoted()})") }
    if (expecting != OK) add(".expecting($expecting)")
    captures.forEach { add(".capture(${it.name}) { ${extractorFor(it.key)} }") }
}

/**
 * A value read out of a JSON body with the standard library and nothing else.
 *
 * The generated file is a caller's file: it takes kestrel-core and kestrel-http
 * and no parser, so an extractor that needed one would be a dependency this
 * module chose on somebody else's behalf.
 */
private fun extractorFor(key: String): String =
    "it.body.substringAfter(\"\\\"$key\\\":\\\"\", \"\").substringBefore('\"').ifEmpty { null }"

private fun todoFor(header: String): String = "the $header header was dropped; see docs/cookbook.md"

/**
 * A plain string where the value needs no escaping, a raw one where it carries
 * quotes or backslashes, and an escaped one split across lines where neither
 * fits.
 *
 * All three are what the value was; the choice is about what a reader of the
 * generated file would have written by hand.
 */
private fun String.quoted(): String = when {
    fitsPlain() -> "\"$this\""
    fitsRaw() -> "\"\"\"$this\"\"\""
    else -> chunked(CHUNK).joinToString(separator = " +\n            ") { "\"${it.escaped()}\"" }
}

/** Nothing in it needs escaping, so a reader would have written it as an ordinary string. */
private fun String.fitsPlain(): Boolean =
    none { it in needsEscaping } && length + PLAIN_QUOTES + INDENT_DEEP <= WIDTH

/** It carries quotes or backslashes, which a raw string says plainly and an escaped one buries. */
private fun String.fitsRaw(): Boolean =
    !contains("\"\"\"") && none { it in cannotBeRaw } && length + RAW_QUOTES + INDENT_DEEP <= WIDTH

private val needsEscaping = charArrayOf('"', '\\', '$', '\n', '\r', '\t')

private val cannotBeRaw = charArrayOf('$', '\n', '\r')

private fun String.escaped(): String = buildString {
    this@escaped.forEach { char ->
        when (char) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '$' -> append("\\$")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(char)
        }
    }
}

private const val OK = 200
private const val WIDTH = 120
private const val PLAIN_QUOTES = 2
private const val RAW_QUOTES = 6

/** Where a step sits, and where the deepest line of one does. */
private const val INDENT = 4
private const val INDENT_DEEP = 30
private const val CHUNK = 80
